app/routes.php
<?php

	Route::get('/', array('uses' => 'ContactsController@index'));
	Route::get('random_contact', array('uses' => 'ContactsController@random'));


	Route::resource('contacts', 'ContactsController');
	Route::resource('personal_contacts', 'PersonalContactsController');
	Route::resource('business_contacts', 'BusinessContactsController');

app/models/Contact.php
<?php

	class Contact extends Eloquent {
		protected $guarded = array();

		public static $rules = array(
			'name' => 'required',
			'email' => 'required|email',
			'number' => 'required|numeric'
		);

	}

app/controllers/ContactsController.php
<?php

	class ContactsController extends BaseController {

		/**
		 * Contact Repository
		 *
		 * @var Contact
		 */
		protected $contact;

		public function __construct(Contact $contact)
		{
			$this->contact = $contact;
		}

		/**
		 * Display a listing of the resource.
		 *
		 * @return Response
		 */
		public function index()
		{
			$contacts = $this->contact->all();

			return View::make('contacts.index', compact('contacts'));
		}

		/**
		 * Show the form for creating a new resource.
		 *
		 * @return Response
		 */
		public function create()
		{
			return View::make('contacts.create');
		}

		/**
		 * Store a newly created resource in storage.
		 *
		 * @return Response
		 */
		public function store()
		{
			$input = Input::all();
			$validation = Validator::make($input, Contact::$rules);

			if ($validation->passes())
			{
				$this->contact->create($input);

				return Redirect::route('contacts.index');
			}

			return Redirect::route('contacts.create')
				->withInput()
				->withErrors($validation)
				->with('message', 'There were validation errors.');
		}

		/**
		 * Display the specified resource.
		 *
		 * @param  int  $id
		 * @return Response
		 */
		public function show($id)
		{
			$contact = $this->contact->findOrFail($id);

			if($contact->personal) {
				$personal = PersonalContact::where('contact_id', '=', $contact->id)->firstOrFail();
				$compact_var = 'personal';
			} else {
				$business = BusinessContact::where('contact_id', '=', $contact->id)->firstOrFail();
				$compact_var = 'business';
			}

			return View::make('contacts.show', compact('contact', $compact_var));
		}

		/**
		 * Display random resource.
		 *
		 * @return Response
		 */
		public function random()
		{
			$contact = Contact::all()->random(1);
			$output["name"] = $contact->name;
			$output["url"] = action('ContactsController@show', $contact->id);
			if($contact->personal) {
				$personal = PersonalContact::where('contact_id', '=', $contact->id)->firstOrFail();
				$output["photo"] = $personal->photo;
			}
			return $output;
		}

		/**
		 * Show the form for editing the specified resource.
		 *
		 * @param  int  $id
		 * @return Response
		 */
		public function edit($id)
		{
			//
		}

		/**
		 * Update the specified resource in storage.
		 *
		 * @param  int  $id
		 * @return Response
		 */
		public function update($id)
		{
			//
		}

		/**
		 * Remove the specified resource from storage.
		 *
		 * @param  int  $id
		 * @return Response
		 */
		public function destroy($id)
		{
			//
		}

	}

app/views/contacts/create.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Create Contact</h1>

{{ Form::open(array('route' => 'contacts.store')) }}
	<ul>
        <li>
            {{ Form::label('name', 'Name:') }}
            {{ Form::text('name') }}
        </li>

        <li>
            {{ Form::label('email', 'Email:') }}
            {{ Form::text('email') }}
        </li>

        <li>
            {{ Form::label('number', 'Number:') }}
            {{ Form::text('number') }}
        </li>

		<li>
			{{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
		</li>
	</ul>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/contacts/index.blade.php
@extends('layouts.scaffold')

@section('sidebar')
<div id="sidebar">
    <h3>Random Contact</h3>
    <a href="#" id="random_url">
        <img src="{{asset('photos/default.jpg')}}" id="random_photo" width="50" height="50">
        <span id="random_name"></span>
    </a>
</div>
@stop

@section('main')

<h1>All Contacts</h1>

<p>{{ link_to_route('personal_contacts.create', 'Add new Personal contact') }} | {{ link_to_route('business_contacts.create', 'Add new Business contact') }} </p>

@if ($contacts->count())
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Number</th>
				<th>Type</th>
				<th>Action</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($contacts as $contact)
				<tr>
					<td>{{{ $contact->name }}}</td>
					<td>{{{ $contact->email }}}</td>
					<td>{{{ $contact->number }}}</td>
					@if ($contact->personal)
                        <td>Personal</td>
                    @else
                        <td>Business</td>
                    @endif
					<td>{{ link_to_route('contacts.show', 'Show', array($contact->id), array('class' => 'btn btn-info')) }}</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@else
	There are no contacts
@endif

@stop

app/views/contacts/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Show Contact</h1>

<p>{{ link_to_route('contacts.index', 'Return to all contacts') }}</p>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Name</th>
            <th>Email</th>
            <th>Number</th>

            @if ($contact->personal)
                <th>Home Address</th>
                <th>Birth day</th>
            @else
                <th>Fax</th>
                <th>Website</th>
            @endif

            <th>Action</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $contact->name }}}</td>
            <td>{{{ $contact->email }}}</td>
            <td>{{{ $contact->number }}}</td>

			@if ($contact->personal)
			    <td>{{{ $personal->home_address }}}</td>
			    <td>{{{ $personal->birth_day }}}</td>
			    <td><!-- Button HTML (to Trigger Modal) -->
                        <a href="#myModal" class="btn btn-primary" data-toggle="modal">Show Photo & Address</a>

                        <!-- Modal HTML -->
                        <div id="myModal" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Photo & Home Address</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>{{{ $personal->home_address }}}</p>
                                        <img src="{{asset('photos/'.$personal->photo)}}" style="max-width: 570px;max-height: 400px;">
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div></td>
			@else
            	<td>{{{ $business->fax }}}</td>
                <td>{{{ $business->website }}}</td>
                <td><a class="btn btn-primary" href="mailto:{{{ $contact->email }}}?Subject=Hello%20iMENA" target="_top">Send Mail</a></td>
            @endif
		</tr>
	</tbody>
</table>

@stop